targets:
  $default:
    sources:
      - lib/**
      - graphql/schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: graphql/schema.graphql
              queries_glob: graphql/queries/**.graphql
              output: lib/data/hashnode_api.dart
