name: hashnode
description: A minimal hashnode client
version: 1.0.6+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  faker: ^2.0.0-rc.2
  flutter_dotenv: ^4.0.0-nullsafety.0
  flutter_markdown: ^0.6.1
  graphql_flutter: ^5.0.0-nullsafety.2
  html2md: ^1.0.1
  intl: ^0.17.0
  logger: ^1.0.0
  mockito: ^5.0.3
  provider: ^5.0.0
  responsive_builder: ^0.4.1
  routemaster: ^0.7.0
  sentry_flutter: ^5.0.0
  timeago: ^3.0.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  grinder: ^0.9.0
flutter:
  uses-material-design: true

  assets:
    - images/
    - .env
